### PR TITLE
feat: Task 4 (documentation)

### PR DESCRIPTION
**Pull request by logotip4ik**

### CODE REVIEW

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
what is html folder for?

**Comment by logotip4ik** [comment]
@andrii-s-spitzer-lpnu-ua these files were generated by doxygen

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
> @andrii-s-spitzer-lpnu-ua these files were generated by doxygen

why do you stored then under git control? They need to be generated each time due actions and stored in arttifacts

**Comment by logotip4ik** [comment]
> > @andrii-s-spitzer-lpnu-ua these files were generated by doxygen
> 
> why do you stored then under git control? They need to be generated each time due actions and stored in arttifacts

Ok, will update my PR

**Comment by logotip4ik** [comment]
@andrii-s-spitzer-lpnu-ua Updated. Generating html documentation in ci and uploading `html` folder as artifact

**Review by andrii-s-spitzer-lpnu-ua — APPROVED** [review]

**Pull request merged**
