### PR TITLE
Task 2

### PR DESCRIPTION
**Pull request by logotip4ik**

### CODE REVIEW

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
where is actions?

**Comment by logotip4ik** [comment]
That's should be actions? They can build binaries and upload them as artifacts, but what tests they should run? Do we really need to add ci to such simple project at this stage ?

**Comment by logotip4ik** [comment]
@andrii-s-spitzer-lpnu-ua

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
> 
> 
> That's should be actions? They can build binaries and upload them as artifacts, but what tests they should run? Do we really need to add ci to such simple project at this stage ?

In this task you are creating desctop client. The action should build exe file and put it into artifacts

**Review by andrii-s-spitzer-lpnu-ua — APPROVED** [review]

**Pull request merged**
