### PR TITLE
feat: task 3

### PR DESCRIPTION
**Pull request by logotip4ik**

### CODE REVIEW

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
where is CI script?

**Comment by logotip4ik** [comment]
@andrii-s-spitzer-lpnu-ua What should be in ci script ?

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
> @andrii-s-spitzer-lpnu-ua What should be in ci script ?

build, device programming, testing

**Comment by logotip4ik** [comment]
> build, device programming, testing

@andrii-s-spitzer-lpnu-ua i can add a build step, but i can't program or test without hardware and i can't connect or add it in ci

**Comment by andrii-s-spitzer-lpnu-ua** [comment]
> > build, device programming, testing
> 
> @andrii-s-spitzer-lpnu-ua i can add a build step, but i can't program or test without hardware and i can't connect or add it in ci
this script should understand where it run:
on github - skip HW logic
on laptop - run all including HW logic

**Review by andrii-s-spitzer-lpnu-ua — APPROVED** [review]

**Pull request merged**
